apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-adapter-back
  labels:
    app: api-adapter-back
  namespace: default
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: api-adapter-back
  template:
    metadata:
      labels:
        app: api-adapter-back
    spec:
      containers:
      - name: api-adapter-back
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/ 
          readOnly: false
          name: back-conf
        - mountPath: /var/log/nginx 
          name: back-log       
      volumes:
      - name: back-conf
        configMap:
          name: api-adapter 
          items:
            - key: back.default.conf
              path: default.conf
      - name: back-log
        emptyDir: {}