
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-adapter
data:
  front.default.conf: |
    proxy_buffering off;
    proxy_redirect off;
    proxy_http_version 1.1; 
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Correlation-ID $pid-$msec-$request_length;
      
    upstream back {
      server api-adapter-back.default.svc.cluster.local:80;
    }

    server {

      rewrite_log on;
      access_log  /var/log/nginx/access.log;
      error_log debug;
      listen 80 ;

      location /health {
        return 200;
        access_log off;
      }

      location / {
        proxy_pass         http://back;
      }
    }
  back.default.conf: |
    server {
      rewrite_log on;
  
      add_header X-Test test;
      access_log  /var/log/nginx/access.log;
      error_log debug;
      listen 80;

      add_header X-Correlation-ID $http_x_correlation_id;
 
      location /health {
        return 200;
        access_log off;
      }

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
      }
    }